### ISSUE TITLE
For better automation, can we include some extra parameters...

### ISSUE THREAD

**Issue by brianlala** [NikCharlebois/SharePointDSC.Reverse#19]
- **Force**: To install missing module packages without prompting (e.g. when removing old module directories). Currently this can cause several prompts in the script (and yeah I know it's my stuff originally :))
- **OutputLocation**: To specify the output path for the resulting .ps1 file without having to wait for the entire script to run and prompt for a location.

And also maybe:

- **FarmName**: To allow for unique output file names (say, if we are using a single location to store a bunch of farm configs, we would want the names to be unique.

Also, maybe let's pop open Explorer when the script is done at the OutputLocation specified so user doesn't have to hunt around for the exported config.

Cheers
Brian

**Comment by NikCharlebois** [comment]
Great feedback dude. Thanks. Instead of -Force, I was however thinking of going wit -Confirm:$false to suppress all prompts.

As for FarmName, if we let OutPutLocation be OutputFile instead, and ask the users to specify the path to the File (including .ps1) that would also take care of it and reduce the overall number of switches. Thoughts?

**Comment by brianlala** [comment]
Yes, -Confirm:$false is definitely better. Also good with OutputFile instead of OutputLocation. Just let's do a Test-Path on the parent location to avoid nasty error messages if user fat-fingers the location, and give them a chance to correct etc.
